"""
Calculate The Debt Coverage Ra System Orchestrator
Auto-generated by Meta-Agent System

Coordinates all agents in a single unified workflow
"""

import os
import sys
from pathlib import Path
from loguru import logger
from datetime import datetime
import json

# Add agents to path
sys.path.insert(0, str(Path(__file__).parent))

from agents.calcagent import Calcagent


class SystemOrchestrator:
    """Orchestrates all agents in a single workflow"""
    
    def __init__(self):
        self.calcagent = Calcagent()
        logger.info("All agents initialized")
    
    def run_analysis(self, **kwargs) -> dict:
        """
        Run complete workflow
        
        Args:
            **kwargs: Input parameters for the workflow
            
        Returns:
            Complete analysis result
        """
        try:
            logger.info("Starting workflow...")
            
            # Execute agents in sequence
            result = self.calcagent.run(**kwargs)
            logger.info(f"✓ CalcAgent completed")
            
            return result
            
        except Exception as e:
            logger.error(f"Workflow failed: {e}")
            raise
    
    def run_batch_analysis(self, inputs: list) -> list:
        """
        Run analysis for multiple inputs
        
        Args:
            inputs: List of input parameter dictionaries
            
        Returns:
            List of analysis results
        """
        results = []
        for idx, input_params in enumerate(inputs, 1):
            try:
                logger.info(f"Processing input {idx}/{len(inputs)}")
                result = self.run_analysis(**input_params)
                results.append(result)
            except Exception as e:
                logger.error(f"Failed to process input {idx}: {e}")
                results.append({"status": "ERROR", "error": str(e)})
        return results
    
    def save_results(self, results: dict, output_file: str = None):
        """Save results to file"""
        if output_file is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_file = f"results/analysis_{timestamp}.json"
        
        # Ensure results directory exists
        Path(output_file).parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, 'w') as f:
            json.dump(results, f, indent=2)
        
        logger.info(f"Results saved to: {output_file}")
        return output_file


def main():
    """Main execution"""
    logger.add("logs/orchestrator.log", rotation="1 day")
    
    orchestrator = SystemOrchestrator()
    
    # Get input from environment or use defaults
    input_params = {}
    for key in os.environ:
        if key.startswith("INPUT_"):
            param_name = key.replace("INPUT_", "").lower()
            input_params[param_name] = os.getenv(key)
    
    # If no inputs provided, use defaults
    if not input_params:
        input_params = {"property_name": "Orlando Fashion Square"}  # Default example
    
    # Run analysis
    logger.info("="*70)
    logger.info("CALCULATE-THE-DEBT-COVERAGE-RA-SYSTEM - Starting Analysis")
    logger.info("="*70)
    
    result = orchestrator.run_analysis(**input_params)
    
    # Save and display results
    output_file = orchestrator.save_results(result)
    
    logger.info("\n" + "="*70)
    logger.info("ANALYSIS COMPLETE")
    logger.info("="*70)
    logger.info(f"\nResults saved to: {output_file}")
    logger.info("="*70)


if __name__ == "__main__":
    main()
