"""
Simulation Runner for Calculate The Debt Coverage Ra System
Auto-generated by Meta-Agent System

Run multiple scenarios and simulations in single container
"""

import sys
from pathlib import Path
from loguru import logger
import json

sys.path.insert(0, str(Path(__file__).parent))

from orchestrator import SystemOrchestrator


def run_scenario_simulation():
    """Run multiple what-if scenarios"""
    
    orchestrator = SystemOrchestrator()
    
    # Define simulation scenarios
    scenarios = [
        {
            "name": "Scenario 1",
            "description": "Base case analysis",
            "params": {"property_name": "Orlando Fashion Square"}
        },
        {
            "name": "Scenario 2",
            "description": "Alternative property",
            "params": {"property_name": "Millenia Mall"}
        }
    ]
    
    logger.info("="*70)
    logger.info("RUNNING SIMULATIONS")
    logger.info("="*70)
    
    results = []
    
    for idx, scenario in enumerate(scenarios, 1):
        logger.info(f"\n--- Scenario {idx}: {scenario['name']} ---")
        logger.info(f"Description: {scenario['description']}")
        
        try:
            result = orchestrator.run_analysis(**scenario['params'])
            result['scenario_name'] = scenario['name']
            result['scenario_description'] = scenario['description']
            results.append(result)
            logger.info(f"✓ {scenario['name']} completed")
        except Exception as e:
            logger.error(f"✗ {scenario['name']} failed: {e}")
    
    # Save simulation results
    output_file = orchestrator.save_results(
        {"scenarios": results, "total_scenarios": len(scenarios)},
        "results/simulation_results.json"
    )
    
    logger.info("\n" + "="*70)
    logger.info("SIMULATION COMPLETE")
    logger.info("="*70)
    logger.info(f"Scenarios run: {len(results)}/{len(scenarios)}")
    logger.info(f"Results: {output_file}")


def run_batch_analysis():
    """Run analysis for multiple inputs"""
    
    orchestrator = SystemOrchestrator()
    
    # Define batch inputs
    inputs = [
        {"property_name": "Orlando Fashion Square"},
        {"property_name": "Millenia Mall"},
        {"property_name": "Florida Mall"}
    ]
    
    logger.info("="*70)
    logger.info("BATCH ANALYSIS")
    logger.info("="*70)
    
    results = orchestrator.run_batch_analysis(inputs)
    
    # Save results
    output_file = orchestrator.save_results(
        {"results": results, "total_inputs": len(inputs)},
        "results/batch_analysis.json"
    )
    
    logger.info("\n" + "="*70)
    logger.info("BATCH ANALYSIS COMPLETE")
    logger.info("="*70)
    logger.info(f"Inputs processed: {len(results)}")
    logger.info(f"Results: {output_file}")


if __name__ == "__main__":
    import sys
    
    mode = sys.argv[1] if len(sys.argv) > 1 else "scenario"
    
    if mode == "scenario":
        run_scenario_simulation()
    elif mode == "batch":
        run_batch_analysis()
    else:
        logger.error(f"Unknown mode: {mode}")
        logger.info("Usage: python run_simulation.py [scenario|batch]")
