"""
Test Script for Generated CalcAgent

This script tests the CalcAgent generated by the Meta-Agent system.
It demonstrates how to use the generated agent in your application.
"""

import os
import sys
from pathlib import Path
from loguru import logger
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add generated agents to path
agents_path = Path(__file__).parent / "generated_agents" / "agents"
sys.path.insert(0, str(agents_path))

# Configure logging
logger.remove()
logger.add(sys.stdout, format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>")
logger.add("logs/calcagent_test.log", rotation="1 MB")

def print_section(title: str):
    """Print a formatted section header"""
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)

def check_database_setup():
    """Check if database is accessible"""
    print_section("Step 1: Checking Database Setup")
    
    db_url = os.getenv('DATABASE_URL')
    if not db_url:
        logger.error("❌ DATABASE_URL not found in .env file")
        return False
    
    logger.info(f"✓ Database URL configured: {db_url.split('@')[1] if '@' in db_url else 'localhost'}")
    
    try:
        import psycopg2
        conn = psycopg2.connect(
            dbname=os.getenv('DB_NAME', 'dscr_poc_db'),
            user=os.getenv('DB_USER', 'postgres'),
            password=os.getenv('DB_PASSWORD', ''),
            host=os.getenv('DB_HOST', 'localhost'),
            port=os.getenv('DB_PORT', '5432')
        )
        conn.close()
        logger.info("✓ Database connection successful")
        return True
    except Exception as e:
        logger.error(f"❌ Database connection failed: {e}")
        logger.warning("Make sure PostgreSQL is running and credentials are correct")
        return False

def check_database_tables():
    """Check if required tables exist"""
    print_section("Step 2: Checking Database Tables")
    
    try:
        import psycopg2
        conn = psycopg2.connect(
            dbname=os.getenv('DB_NAME', 'dscr_poc_db'),
            user=os.getenv('DB_USER', 'postgres'),
            password=os.getenv('DB_PASSWORD', ''),
            host=os.getenv('DB_HOST', 'localhost'),
            port=os.getenv('DB_PORT', '5432')
        )
        cursor = conn.cursor()
        
        # Check for properties table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'properties'
            );
        """)
        has_properties = cursor.fetchone()[0]
        
        # Check for financials table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'financials'
            );
        """)
        has_financials = cursor.fetchone()[0]
        
        if has_properties:
            logger.info("✓ 'properties' table exists")
        else:
            logger.warning("⚠ 'properties' table not found")
        
        if has_financials:
            logger.info("✓ 'financials' table exists")
        else:
            logger.warning("⚠ 'financials' table not found")
        
        conn.close()
        return has_properties and has_financials
        
    except Exception as e:
        logger.error(f"❌ Failed to check tables: {e}")
        return False

def test_calcagent_import():
    """Test if CalcAgent can be imported"""
    print_section("Step 3: Testing CalcAgent Import")
    
    try:
        from calcagent import CalcAgent, Config
        logger.info("✓ CalcAgent imported successfully")
        logger.info(f"  Module location: {agents_path / 'calcagent.py'}")
        return True
    except ImportError as e:
        logger.error(f"❌ Failed to import CalcAgent: {e}")
        return False
    except Exception as e:
        logger.error(f"❌ Unexpected error during import: {e}")
        return False

def test_calcagent_initialization():
    """Test if CalcAgent can be initialized"""
    print_section("Step 4: Testing CalcAgent Initialization")
    
    try:
        from calcagent import CalcAgent, Config
        
        # Create minimal config
        config = Config(
            agent_name="CalcAgent",
            version="1.0.0",
            description="DSCR Calculation Agent",
            role="primary_agent",
            capabilities={},
            data_sources={},
            workflow={},
            performance={},
            logging={},
            testing={}
        )
        
        agent = CalcAgent(config)
        logger.info("✓ CalcAgent initialized successfully")
        logger.info(f"  Agent Name: {agent.config.agent_name}")
        logger.info(f"  Version: {agent.config.version}")
        return agent
        
    except Exception as e:
        logger.error(f"❌ Failed to initialize CalcAgent: {e}")
        return None

def test_calcagent_execution(agent, property_id="PROP001"):
    """Test CalcAgent execution with a property ID"""
    print_section(f"Step 5: Testing CalcAgent Execution (Property: {property_id})")
    
    try:
        result = agent.run(property_id)
        logger.info(f"✓ CalcAgent executed successfully")
        logger.info(f"  Result: {result}")
        return True
    except Exception as e:
        logger.error(f"❌ CalcAgent execution failed: {e}")
        logger.error(f"  Error type: {type(e).__name__}")
        return False

def main():
    """Main test execution"""
    print("\n" + "=" * 70)
    print("  GENERATED CALCAGENT - TEST SUITE")
    print("=" * 70)
    print(f"\n📁 Testing agent from: {agents_path}")
    print(f"📄 Specification: agent_specs/calcagent.yaml")
    print(f"🐍 Implementation: generated_agents/agents/calcagent.py\n")
    
    # Track test results
    tests_passed = 0
    tests_total = 5
    
    # Test 1: Database setup
    if check_database_setup():
        tests_passed += 1
    else:
        logger.warning("⚠ Skipping remaining tests due to database setup failure")
        print_section("Test Summary")
        logger.info(f"Tests Passed: {tests_passed}/{tests_total}")
        return False
    
    # Test 2: Database tables
    if check_database_tables():
        tests_passed += 1
    else:
        logger.warning("⚠ Database tables not set up. Run the SQL setup script first.")
        logger.info("\nSee GENERATED_AGENT_QUICKSTART.md for setup instructions")
    
    # Test 3: Import
    if test_calcagent_import():
        tests_passed += 1
    else:
        logger.warning("⚠ Skipping remaining tests due to import failure")
        print_section("Test Summary")
        logger.info(f"Tests Passed: {tests_passed}/{tests_total}")
        return False
    
    # Test 4: Initialization
    agent = test_calcagent_initialization()
    if agent:
        tests_passed += 1
    else:
        logger.warning("⚠ Skipping execution test due to initialization failure")
        print_section("Test Summary")
        logger.info(f"Tests Passed: {tests_passed}/{tests_total}")
        return False
    
    # Test 5: Execution
    if test_calcagent_execution(agent):
        tests_passed += 1
    
    # Summary
    print_section("Test Summary")
    logger.info(f"Tests Passed: {tests_passed}/{tests_total}")
    
    if tests_passed == tests_total:
        logger.info("✅ All tests passed! CalcAgent is working correctly.")
        return True
    elif tests_passed >= 3:
        logger.warning("⚠ Partial success. Some tests passed but database setup needed.")
        return False
    else:
        logger.error("❌ Multiple tests failed. Check logs above for details.")
        return False

if __name__ == "__main__":
    try:
        success = main()
        print("\n" + "=" * 70)
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⚠ Test interrupted by user")
        sys.exit(130)
    except Exception as e:
        logger.error(f"❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

